Add season and episode to title
Bonfra04/Stronzflix pull request #49
Opened 2024-08-25 17:05 UTC by R1D3R175

Closes #38 

![image](https://github.com/user-attachments/assets/f18b2c9d-9943-467d-b553-8fa8ca2ebe79)

2024-08-29 17:02 UTC, Bonfra04 commented
Hi, thanks for the PR.
Some of the files you changed were moved into another repo ([StronzVideoPlayer](https://github.com/StronzLabs/StronzVideoPlayer)). Could you adjust this PR considering the separation made and open a new PR there with the relevant changes? thanks

2024-08-29 21:05 UTC, Bonfra04 requested changes

2024-08-29 21:05 UTC, Bonfra04 commented on lib/backend/api/bindings/streamingcommunity.dart
> +                seasonNo: index + 1,
Here use `seasonObject["number"]` instead of the index. Indexes are prone to errors and the propertiy already exists.

2024-08-29 21:05 UTC, Bonfra04 commented on lib/backend/api/bindings/streamingcommunity.dart
> +            dynamic seasonObject = title["seasons"][index];
This indexing is rendered useless by the for-each that should be implemented as noted above.

2024-08-29 21:05 UTC, Bonfra04 commented on lib/components/player/media_title.dart
> +                )
All of this should be a different pull request in the specific repository [StronzVideoPlayer](https://github.com/StronzLabs/StronzVideoPlayer)

2024-08-29 21:05 UTC, Bonfra04 commented on lib/components/player/stronzflix_player_controller.dart
> +    bool get isEpisode => this._watchable is Episode;
the video player should be agnostic of episodes and, more in general, any kind of subclass of watchable

2024-08-29 21:05 UTC, Bonfra04 commented on lib/components/player/stronzflix_player_controller.dart
> +
for the same reason as above this code has to be moved in the `media.dart` file and not in the videoplayer as it is specific to subclasses of whatchable

2024-08-29 21:05 UTC, Bonfra04 commented on lib/components/player/stronzflix_player_controller.dart
> +
If any of this still remains in this file and is not moved into the correct place, it should be a PR to the video player repository cited above and not this one.

2024-08-30 15:28 UTC, closed without merging

2024-08-30 15:29 UTC, R1D3R175 commented
Closed since it would be too hard to adapt on current code, will redo it in the future